language: python
dist: xenial
sudo: required
env:
python:
    - "3.6"
    - "3.7"
    - "3.7-dev"
install:
    - "make setup"
    - "pip install ."
script:
    - "make test"
matrix:
    allow_failures:
        - python: "3.7-dev"
    include:
        - python: "3.7"
          env: LINTING=true
          script:
              - "make lint test"
